# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiceWareMainWindow_v01.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_LanguageLists = QtWidgets.QHBoxLayout()
        self.horizontalLayout_LanguageLists.setObjectName("horizontalLayout_LanguageLists")
        self.verticalLayout_LanguagesCheckBoxes = QtWidgets.QVBoxLayout()
        self.verticalLayout_LanguagesCheckBoxes.setObjectName("verticalLayout_LanguagesCheckBoxes")
        self.checkBox_english = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_english.setObjectName("checkBox_english")
        self.verticalLayout_LanguagesCheckBoxes.addWidget(self.checkBox_english, 0, QtCore.Qt.AlignTop)
        self.checkBox_french = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_french.setObjectName("checkBox_french")
        self.verticalLayout_LanguagesCheckBoxes.addWidget(self.checkBox_french)
        self.checkBox_german = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_german.setObjectName("checkBox_german")
        self.verticalLayout_LanguagesCheckBoxes.addWidget(self.checkBox_german)
        self.horizontalLayout_LanguageLists.addLayout(self.verticalLayout_LanguagesCheckBoxes)
        self.pushButton_LoadAdditionalWordList = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LoadAdditionalWordList.setObjectName("pushButton_LoadAdditionalWordList")
        self.horizontalLayout_LanguageLists.addWidget(self.pushButton_LoadAdditionalWordList, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout_LanguageLists)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_ = QtWidgets.QVBoxLayout()
        self.verticalLayout_.setObjectName("verticalLayout_")
        self.horizontalLayout_Options = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Options.setObjectName("horizontalLayout_Options")
        self.verticalLayout_Separator = QtWidgets.QVBoxLayout()
        self.verticalLayout_Separator.setObjectName("verticalLayout_Separator")
        self.label_Separator = QtWidgets.QLabel(self.centralwidget)
        self.label_Separator.setObjectName("label_Separator")
        self.verticalLayout_Separator.addWidget(self.label_Separator)
        self.lineEdit_Separator = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Separator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Separator.setObjectName("lineEdit_Separator")
        self.verticalLayout_Separator.addWidget(self.lineEdit_Separator)
        self.horizontalLayout_Options.addLayout(self.verticalLayout_Separator)
        self.verticalLayout_WordCount = QtWidgets.QVBoxLayout()
        self.verticalLayout_WordCount.setObjectName("verticalLayout_WordCount")
        self.label_WordCount = QtWidgets.QLabel(self.centralwidget)
        self.label_WordCount.setObjectName("label_WordCount")
        self.verticalLayout_WordCount.addWidget(self.label_WordCount)
        self.spinBox_WordCount = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_WordCount.setObjectName("spinBox_WordCount")
        self.verticalLayout_WordCount.addWidget(self.spinBox_WordCount)
        self.horizontalLayout_Options.addLayout(self.verticalLayout_WordCount)
        self.verticalLayout_SpecialCharsToAdd = QtWidgets.QVBoxLayout()
        self.verticalLayout_SpecialCharsToAdd.setObjectName("verticalLayout_SpecialCharsToAdd")
        self.label_SpecialCharsToAdd = QtWidgets.QLabel(self.centralwidget)
        self.label_SpecialCharsToAdd.setObjectName("label_SpecialCharsToAdd")
        self.verticalLayout_SpecialCharsToAdd.addWidget(self.label_SpecialCharsToAdd)
        self.spinBox_SpecialCharsToAdd = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_SpecialCharsToAdd.setObjectName("spinBox_SpecialCharsToAdd")
        self.verticalLayout_SpecialCharsToAdd.addWidget(self.spinBox_SpecialCharsToAdd)
        self.horizontalLayout_Options.addLayout(self.verticalLayout_SpecialCharsToAdd)
        self.verticalLayout_NumbersToAdd = QtWidgets.QVBoxLayout()
        self.verticalLayout_NumbersToAdd.setObjectName("verticalLayout_NumbersToAdd")
        self.label_NumbersToAdd = QtWidgets.QLabel(self.centralwidget)
        self.label_NumbersToAdd.setObjectName("label_NumbersToAdd")
        self.verticalLayout_NumbersToAdd.addWidget(self.label_NumbersToAdd)
        self.spinBox_NumbersToAdd = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_NumbersToAdd.setObjectName("spinBox_NumbersToAdd")
        self.verticalLayout_NumbersToAdd.addWidget(self.spinBox_NumbersToAdd)
        self.horizontalLayout_Options.addLayout(self.verticalLayout_NumbersToAdd)
        self.verticalLayout_.addLayout(self.horizontalLayout_Options)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_.addWidget(self.line_2)
        self.horizontalLayout_PassPhrase = QtWidgets.QHBoxLayout()
        self.horizontalLayout_PassPhrase.setObjectName("horizontalLayout_PassPhrase")
        self.verticalLayout_PassPhraseLabel = QtWidgets.QVBoxLayout()
        self.verticalLayout_PassPhraseLabel.setObjectName("verticalLayout_PassPhraseLabel")
        self.label_PassPhrase = QtWidgets.QLabel(self.centralwidget)
        self.label_PassPhrase.setObjectName("label_PassPhrase")
        self.verticalLayout_PassPhraseLabel.addWidget(self.label_PassPhrase)
        self.textEdit_PassPhrase = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_PassPhrase.setObjectName("textEdit_PassPhrase")
        self.verticalLayout_PassPhraseLabel.addWidget(self.textEdit_PassPhrase)
        self.horizontalLayout_PassPhrase.addLayout(self.verticalLayout_PassPhraseLabel)
        self.pushButton_MakeNewPassPhrase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_MakeNewPassPhrase.setObjectName("pushButton_MakeNewPassPhrase")
        self.horizontalLayout_PassPhrase.addWidget(self.pushButton_MakeNewPassPhrase, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_.addLayout(self.horizontalLayout_PassPhrase)
        self.verticalLayout.addLayout(self.verticalLayout_)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_english.setText(_translate("MainWindow", "english"))
        self.checkBox_french.setText(_translate("MainWindow", "french"))
        self.checkBox_german.setText(_translate("MainWindow", "german"))
        self.pushButton_LoadAdditionalWordList.setText(_translate("MainWindow", "Load additional Word List"))
        self.label_Separator.setText(_translate("MainWindow", "Seperator"))
        self.label_WordCount.setText(_translate("MainWindow", "Word count for pass phrase"))
        self.label_SpecialCharsToAdd.setText(_translate("MainWindow", "Amount of special characters to add"))
        self.label_NumbersToAdd.setText(_translate("MainWindow", "Amount of numbrs to add"))
        self.label_PassPhrase.setText(_translate("MainWindow", "Pass phrase"))
        self.pushButton_MakeNewPassPhrase.setText(_translate("MainWindow", "Make new Pass phrase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

